[aliases]
sh = "sh_musl"
cowsay = "cowsay_quay"

[containers.sh_musl]
image = "registry://quay.io/libpod/alpine@sha256:fa93b01658e3a5a1686dc3ae55f170d8de487006fb53a28efcd12ab0710a2e5f"
cmd = ["sh"]
[containers.sh_musl.links]
cowsay = "cowsay_quay"
tuxsay = "tuxsay_quay"

[containers.sh_libc]
image = "registry://quay.io/libpod/ubuntu:latest"
cmd = ["sh"]
[containers.sh_libc.links]
cowsay = "cowsay_quay"
tuxsay = "tuxsay_quay"

# TODO fix docker registry login
# [containers.sh_libc]
# image = "registry://ubuntu:latest"
# cmd = ["sh"]
# [containers.sh_libc.links]
# cowsay = "cowsay_quay"
# tuxsay = "tuxsay_quay"

[containers.cowsay_docker]
image = "registry://rancher/cowsay"
cmd = ["cowsay"]
[containers.cowsay_docker.env]
COWSAY_ANIMAL = "tux"

# TODO fix manifest parsing
[containers.cowsay_latest]
image = "registry://quay.io/paper/cowsay:latest"
cmd = ["cowsay"]

[containers.cowsay_quay]
image = "registry://quay.io/paper/cowsay@sha256:432bef5c9fd8e2e4dbc62cd18145f9a3b7f01b8db5195c59d7ddb6cc0facd744"
cmd = ["cowsay"]

[containers.tuxsay_quay]
image = "registry://quay.io/paper/cowsay@sha256:432bef5c9fd8e2e4dbc62cd18145f9a3b7f01b8db5195c59d7ddb6cc0facd744"
cmd = ["cowsay"]

[containers.tuxsay_quay.env]
COWSAY_ANIMAL = "tux"

[volumes]
