[aliases]
bash = "bash"
cowsay = "cowway_container"

[containers.bash]
args = []
cmd = "bash"
image = "bash:latest"
[containers.bash.links]
cowsay = "cowway_container"

[containers.composer]
cmd = "composer"
image = "composer:latest"
[containers.composer.links]
bash = "bash"
[containers.composer.volumes]
"/dir/in/container" = "${PWD}/other/folder"

[containers.cowway_container]
cmd = "cowsay"
image = "jtcressy/cowsay:latest"
[containers.cowway_container.envvars]
COWSAY_ANIMAL = "tux"
