# [[aliases]]
# alias = "composer install"
# command = "docker run --rm --interactive --tty --volume ${PWD}:/app composer install"

[[aliases]]
alias = "dps"
command = "docker ps"


[[aliases]]
alias = "pi"
command = "php -i"

[[aliases]]
alias = "test"
command = "explorer"

[[aliases]]
alias = "pe"
command = "printenv"

[[aliases]]
alias = "co"
command = "code"