group_imports = "StdExternalCrate"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
unstable_features = true
use_try_shorthand = true
