[package]
name = "doe"
version = "0.1.0"
authors = ["Patrick Berenschot <patrick@insiders.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.6"
serde = "1.0.111"
serde_derive = "1.0.111"
shellexpand = "2.0.0"
#walkdir = "2.3.1"