[package]
name = "doe"
version = "0.1.0"
homepage = "https://waaghals.dev/doe"
authors = ["Patrick \"Waaghals\" Berenschot <waaghals@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# nom = "5"
serde = "1.0.111"
serde_derive = "1.0.111"
bollard = "0.11"
tokio = { version = "1.8.1", features = ["rt", "macros"] }
reqwest = { version = "0.11.4", features = ["rustls-tls"] }
termion = "1.5.6"
futures-util = "0.3.15"
structopt = "0.3"
anyhow = "1.0"
nix = "0.22.0"
log = "0.4.14"
clap-verbosity-flag = "0.3.1"
simplelog = "0.10.0"
serde_json = "1.0.66"
regex = "1.5.4"
async-trait = "0.1.51"
bytes = "1.0.1"
sha2 = "0.9.5"
flate2 = "1.0.20"
# shellexpand = "2.0.0"
# walkdir = "2.3.1"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1