[build]
target = "x86_64-unknown-linux-gnu"

[target.i686-unknown-linux-gnu]
[target.x86_64-unknown-linux-gnu]
[target.aarch64-unknown-linux-gnu]

[target.i686-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]
[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]
[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-apple-darwin]
[target.aarch64-apple-darwin]

[target.i686-pc-windows-msvc]
[target.x86_64-pc-windows-msvc]
[target.aarch64-pc-windows-msvc]
