on: [push]

name: Cargo build

jobs:
  build:
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu]
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target {{ matrix.target }}
